config/routes.rb
Rr48rails2013::Application.routes.draw do
  resources :ninjas

  resources :teams

  root 'site#index'

  get 'trailer' => 'site#landing_page'

  

end

app/models/facebook_faces.rb
require 'koala'

class FacebookFaces

  def self.all
    Rails.cache.fetch("FacebookFacesAll", :expires_in => 12.hours) do
      oauth = Koala::Facebook::OAuth.new
      fb = Koala::Facebook::API.new(oauth.get_app_access_token)
      fb.get_connections('222866994508573','members').map {|person| {:name => person["name"], :src => fb.get_picture(person["id"], type: 'square')} }
    end
  end
end

app/models/ninja.rb
require 'twitter'
require 'koala'

class Ninja < ActiveRecord::Base
  belongs_to :team


  def face 
    Rails.cache.fetch("ninjaFace#{id}", :expires_in => 12.hours) do       
      unless twitter.blank?
        Twitter.user(twitter).profile_image_url()
      else unless facebook.blank?
        Koala::Facebook::API.new.get_picture(facebook)  
      end 
      end
    end
  end

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :ninjas

  def to_param
    name
  end

end

app/models/tweets.rb
require 'twitter'

class Tweets

  def self.last(n=1)
    @tweets = Twitter.user_timeline('48rails').first(n)
  end

end



class Twitter::Tweet

  def to_html
    html = self.full_text
    entities = []
    [:user_mentions, :hashtags, :urls, :media].each do |t|
      self[t].each do |e|
        text = full_text[e.indices[0]...e.indices[1]]
        text_html = self.class.send(t.to_s + '_to_html', text, e)
        entities << {text: text, html: text_html, insertion_index: e.indices[0]}
      end
    end
    entities.sort! {|a, b| a[:insertion_index] <=> b[:insertion_index]}

    offset = 0
    entities.each do |e|
      html.slice!(e[:insertion_index] + offset, e[:text].length)
      html.insert(e[:insertion_index] + offset, e[:html])
      offset = offset + e[:html].length - e[:text].length
    end
    html
  end

  def status_url
    "http://twitter.com/48rails/status/#{self.id}"
  end

  private

    def self.user_mentions_to_html(string, entity)
      "<a href='http://twitter.com/#{entity.screen_name}' target='_blank'>#{string}</a>"
    end

    def self.hashtags_to_html(string, entity)
      "<a href='http://twitter.com/search?q=%23#{entity.text}' target='_blank'>#{string}</a>"
    end

    def self.urls_to_html(string, entity)
      "<a href='#{entity.url}' target='_blank'>#{entity.display_url}</a>"
    end

    def self.media_to_html(string, entity)
      "<img src='#{entity.media_url}' alt='#{string}' />"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['USERNAME'] && password == ENV['PASSWORD']
    end
  end

end

app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController
  before_filter :authenticate
  before_action :set_ninja, only: [:show, :edit, :update, :destroy]

  # GET /ninjas
  # GET /ninjas.json
  def index
    @ninjas = Ninja.all
  end

  # GET /ninjas/1
  # GET /ninjas/1.json
  def show
  end

  # GET /ninjas/new
  def new
    @ninja = Ninja.new
  end

  # GET /ninjas/1/edit
  def edit
  end

  # POST /ninjas
  # POST /ninjas.json
  def create
    @ninja = Ninja.new(ninja_params)

    respond_to do |format|
      if @ninja.save
        format.html { redirect_to @ninja, notice: 'Ninja was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ninja }
      else
        format.html { render action: 'new' }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ninjas/1
  # PATCH/PUT /ninjas/1.json
  def update
    respond_to do |format|
      if @ninja.update(ninja_params)
        format.html { redirect_to @ninja, notice: 'Ninja was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninjas/1
  # DELETE /ninjas/1.json
  def destroy
    @ninja.destroy
    respond_to do |format|
      format.html { redirect_to ninjas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ninja
      @ninja = Ninja.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ninja_params
      params.require(:ninja).permit(:name, :twitter, :facebook, :team_id, :prize_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @teams = Team.order(:sort)
    @faces = FacebookFaces.all
    @tweets = Tweets.last(3)

  end

  def landing_page
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate, except: :show
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team }
      else
        format.html { render action: 'new' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find_by(name: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :colour, :order, :prize_id, :hashtag, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ninjas_helper.rb
module NinjasHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title 48rails 2013
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag
  
    %meta{:name=>"viewport", :content=>"width=device-width"}

    = yield :facebook_opengraph
    %meta{property: 'fb:admins', content: '100000163155754'}

    - if Rails.env.production?
      :javascript

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-34709010-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

  = yield

app/views/ninjas/_form.html.haml
= form_for @ninja do |f|
  - if @ninja.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ninja.errors.count, "error")} prohibited this ninja from being saved:"
      %ul
        - @ninja.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :twitter
    = f.text_field :twitter
  .field
    = f.label :facebook
    = f.text_field :facebook
  .field
    = f.label :team_id
    = f.text_field :team_id
  .field
    = f.label :prize_id
    = f.text_field :prize_id
  .actions
    = f.submit 'Save'

app/views/ninjas/edit.html.haml
%h1 Editing ninja

= render 'form'

= link_to 'Show', @ninja
\|
= link_to 'Back', ninjas_path

app/views/ninjas/index.html.haml
%h1 Listing ninjas

%table
  %tr
    %th Name
    %th Twitter
    %th Facebook
    %th Team
    %th Prize
    %th
    %th
    %th

  - @ninjas.each do |ninja|
    %tr
      %td= ninja.name
      %td= ninja.twitter
      %td= ninja.facebook
      %td= ninja.team_id
      %td= ninja.prize_id
      %td= link_to 'Show', ninja
      %td= link_to 'Edit', edit_ninja_path(ninja)
      %td= link_to 'Destroy', ninja, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Ninja', new_ninja_path

app/views/ninjas/new.html.haml
%h1 New ninja

= render 'form'

= link_to 'Back', ninjas_path

app/views/ninjas/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ninja.name
%p
  %b Twitter:
  = @ninja.twitter
%p
  %b Facebook:
  = @ninja.facebook
%p
  %b Team:
  = @ninja.team_id
%p
  %b Prize:
  = @ninja.prize_id

= link_to 'Edit', edit_ninja_path(@ninja)
\|
= link_to 'Back', ninjas_path

app/views/site/_discount.html.haml
:plain
  <!--    
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,+7~,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,D   .MM   M,,,M    M.   MNMMM   :MM   M,M7     MN,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,M   M:   M,,,M    M    M. .M.   MM   MM      . ?O,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,M   M   M,,,MM    M    M   M     M   MM    M    M,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,~N  :   M,MMOM    M    M   M     M   MM    M    M,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,M     ZMMI..M    M    M  DM         MM    M    MMM,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,7I    M...  M    M    M  .M         MM    M    M.IMMO:,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,M   ~$     M    M    M   M   7     MM    M    M  . ZMM,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,,M   ~      M    M    M   M   7:    MM    M    M$    .~MM:,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,:~M   ~      M    N    N   M   7M    MM    N    N ...  ..~MN,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,,MM   ~      .M       M    M   7M    M M      :M OM.  .   .MM,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,MM~7$$?      .  MMMMN      ,I$$+ ?Z$7~ .=MMMMD  $..         $M,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,M,                         ==8M=  =?    . N   O.            .?M:,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,MM                             . .M  M=    .,,. .             .=M,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,~M.                       ..:8?:DO  N.~MM8    M8     . ?.        OM,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,:MO                        .N .MM,  O ~ .MMD$.M.D. ..:MM           MM,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,$M.                        .. NMMM:  Z.O.8MMNM:.  .DMM.  . :?.     .M$,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,MO                         .   MM?8. O  .MMN= .DO N :..DZ+,N,.I.    +M,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,:M.                           +:?.. =7 . 8N..IM~....D M. ?.:..~     . M8,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,MM                         . N.. .  ...$$   .O ..OD8. M:. MMM+ Z      OM,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,M+                          .N.MMMM7+ .   .      . 7~7.. .DMMD ~       M,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,OM .                        ~            8           .$, ?:,I :.        MM,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                          .M~ ., :MI$M.  ..        ..M?. . .          OM,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                               .+.      ..M~.,O ..    ?  =8Z.         :M,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                                          M=ND: I .  ~I               :M,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                                        .M8=8::N8:~.Z .N..            :M,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                                         M.     ZO?=. D?O             :M,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MN                                        .NMMDD+ .      O..            ?M,,,,,,
  ,,,,,,,,,,,,,,,,,,,,MM                                        N.   .OI~.      ?.            NM,,,,,,
  ,,,,,,,,,,,,,,,,,,,,OM..                                     .:.7 .  .N .. ..=,             MN,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,M                     .                .$+.  .. .+MDMMMM.              M~,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,M7.            =            . .         IMNMMMN .7O .MMN.             ~M,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,MM.                         ..          .MMMM,  . ,8OOZ+: .           MM,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,OM                                     .$OM +  =8DMM..,M7M.          .M7,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,M..                       O           .$O...NZN..MIMM.M7            .M,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,MM.                                    D..M .?$Z.,:7O.+:           .DM,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,+M.                  =                :MM7$I~.: ...MI.M,           .MN,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,MM.                                  MINMMMMN.8ND8M.D=.          .?M,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,MM.                              ..D.O,.D+..M +IM7M D...         M7,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,MM.                              .  .  I~ N.M?$. M.          ..MN:,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,:MM8                             Z. 8 .   :D,:I. D.        . ~M+,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,,:+MMM8                       :  $ ~M.,=    .   . D.         DM=,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,,=MM  .ZMM.                  .M..,.~N= ~MMM8,     MM.       IMM,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,,,MM. .  . .MMO               :M   ,$..   ..   +NNN,.ID     :MM:,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,,,MM~.        . 7MM$          NN,.  :D           .  .   M  +MMM,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,,,DM$.  .MM8      ...OMMM?    MMN     M                 ..MMMZ,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,,,IMM..    ..M8         . .NMMM8M..     ..?.           ..OMMD:,,:,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,,,,=MM..        .MM.          ..  ~NMMMMMMMMNND$+~::~+8MMMMM+,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ,,,,,,,,,,,,:~MM .          ..,M=                ..      ..MM7===~,,,,,:,,,,,,,,,,,,,,,,,Z,,,,,,,,,,
  ,,,,,,,,,,,=MM...             . MM.                      ~MM,,,,,,,,,,,,,,,,,,,,,,,NM,,,:M,,,,,,,,,,
  ,,,,,,,,,,MM . ?      +M M   MM:    :M ZN     M  M.    MNM   M    ,   M8.  M       M+MMMMM+M~,,,,,,,
  ,,,,,,,,:MO.   7        DM   M       : :   O   MM   N   MM   M  . ?    M   M       MZM:8MMM,,,,,,,,,
  ,,,,,,,,MD     7   ~M   MM   M.  M8   7   :M   MM   M   8M   M    :    M   M,M  .M,MM,,,,,,,,,,,,,,,
  ,,,,,,~M$ .    7   ~M   MM   M~    M~ M   :M   MM   M   7M   M    M      . M,M  .MM:,,,,,,,,,,,,,,,,
  ,,,,:,M:.      7   ~M   MM   M7M     M    :     M   M   7M   M    ,        M,M   M,,,,,,,,,,,,,,,,,,
  ,,,,,M$.       7   ~M   MM   MMMMM    O   :M   MM   M   7M   M    ,   7    MMM   M,,,,,,,,,,,,,,,,,,
  ,,,MM, .       7   ~M   MM   M   8M   M   :M   MM   M   8M   M    ,   M    M,M   M,,,,,,,,,,,,,,,,,,
  ,?MD..         7        NM   M7       O+   :   MM   ~   MZ       :,   M:   M,M   M,,,,,,,,,,,,,,,,,,
  MM .           ?      :M M   M?M    ~M 7M   .+M.,M.    M,,NO    M$,   MM  .N,M   M,,,,,,,,,,,,,,,,,,
  M..           .                             ...:M7,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
  ...                                         ..,M8,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,=,,,,,,,,.,
  ...                                         .,MN,,,,,,,,,,,,,,,,,,,,,,,,....,.:::,7==~Z+??:~+...,.:,
  ...                                        .,8M,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
                                                              sorry you are late. try harder next year                                                               
  -->

app/views/site/_footer.html.haml
%footer.rows-footer
  48rails by
  %a{href: 'http://www.programmersinpadua.it'} Programmers in Padua
  &middot;
  Follow
  %a{href: 'http://twitter.com/48rails'} @48rails
  &middot;
  Reach us at
  %a{href: 'mailto:ninja@48rails.it'} ninja@48rails.it
  &middot;
  %a{href: 'http://2012.48rails.it/?lang=en'} 2012 Edition
  &middot;
  missed our  
  = link_to 'awesome trailer?', trailer_path

app/views/site/landing_page.html.haml
%body.landing-page

  .landing-page-spotlight
    = image_tag 'ninja-standing-with-sword.png', class: 'landing-page-spotlight-ninja'
    
    .landing-page-spotlight-column

      = image_tag '48rails-logo-2.png', class: 'landing-page-spotlight-logo'

      %p 
        Next 19&ndash;20 October the top Italian Rails devs will gather in Padua to fight the 
        %a{href: 'http://railsrumble.com'} RailsRumble 
        in a 48 hours long non-stop hackathon.

      = image_tag 'ninja+railsrumble.png', style: 'opacity: .7;'

      %p= link_to 'Buy a ticket now!', root_path, class: 'btn landing-page-get-ticket'

      -#:plain
      -#  <!-- Begin MailChimp Signup Form -->
      -#  <div id="mc_embed_signup">
      -#  <form action="http://48rails.us7.list-manage2.com/subscribe/post?u=db3b7f8dab9a0992a4c727698&amp;id=168732f43a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
      -#    
      -#  <div class="mc-field-group inline-field">
      -#    <label for="mce-EMAIL">Email Address </label>
      -#    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="leave your email">
      -#  </div>
      -#  <div class="clear inline-submit"><input type="submit" value="Join us" name="subscribe" id="mc-embedded-subscribe" class="button btn"></div>
      -#    <div id="mce-responses" class="clear">
      -#      <div class="response" id="mce-error-response" style="display:none"></div>
      -#      <div class="response" id="mce-success-response" style="display:none"></div>
      -#    </div>
      -#  </form>
      -#  </div>
      -#
      -#  <!--End mc_embed_signup-->

  .teaser
    = image_tag 'ninja-knelt-with-sword.png', class: 'teaser-image', :'data-order' => '1'
    %p.teaser-text{:'data-order' => '1'} Rails ninjas
    = image_tag 'ninja-kicking.png', class: 'teaser-image', :'data-order' => '2'
    %p.teaser-text{:'data-order' => '2'} are back
    = image_tag 'ninja-jumping-left.png', class: 'teaser-image', :'data-order' => '3'
    %p.teaser-text{:'data-order' => '3'} October 19&ndash;20 
    = image_tag 'ninja-standing-with-sword.png', class: 'teaser-image', :'data-order' => '4'
    %p.teaser-text{:'data-order' => '4'} Padua, Italy 
    %p.teaser-text{:'data-order' => '5'} Hacking non-stop
    %p.teaser-text{:'data-order' => '6'} for 48 hours
    %p.teaser-text{:'data-order' => '7'} The top Italian Rails devs
    %p.teaser-text{:'data-order' => '8'} The top Italian Rails firms
    = image_tag '48rails-logo-2.png', class: 'teaser-image', :'data-order' => '5'
    %p.teaser-text{:'data-order' => '9'} Show your craft
    %p.teaser-text{:'data-order' => '10'} Win our prizes
    %p.teaser-text{:'data-order' => '11'} Earn the glory
    %p.teaser-text{:'data-order' => '12'} Are you ready?

    :javascript  

      var autoplay = true;
      var query = window.location.search.replace('?','');
      if (query.length !== 0) {
        var query_autoplay = query.match(/(autoplay=)[\S][^&]+/)
        if (query_autoplay !== null && query_autoplay[0].split('=')[1] === 'false') autoplay = false
      }

      if(window.matchMedia("(min-width: 769px)").matches) {
        new window.LazyLoad('http://www.youtube.com/iframe_api');
        if(autoplay === true) {
          $('.landing-page-spotlight').hide();
          $('.teaser').show();
        }
      }

      var teaser_animation;
      function onYouTubeIframeAPIReady() { 
        teaser_animation = new window.TeaserAnimation($('.teaser'), {'autoplay': autoplay});
        
        teaser_animation.on_animation_start( function() { 
          $('.landing-page-spotlight').hide(); $('.teaser').show(); 
        });
        
        teaser_animation.on_animation_end( function() { 
          $('.teaser').fadeOut(500, function() { $('.landing-page-spotlight').fadeIn(500); });
        });
      }


  %footer.landing-page-footer
    48rails by
    %a{href: 'http://www.programmersinpadua.it'} Programmers in Padua
    &middot;
    Follow
    %a{href: 'http://twitter.com/48rails'} @48rails
    &middot;
    Reach us at
    %a{href: 'mailto:ninja@48rails.it'} ninja@48rails.it
    &middot;
    %a{href: 'http://2012.48rails.it/?lang=en'} 2012 Edition
    &middot;
    %a{href: '/'} 2013 Edition

    %span.teaser-animation-controls
      %a.teaser-animation-control-play{href: 'javascript:void(0)', onclick: 'teaser_animation.play();', title: 'wanna play our awesome animation?'} &middot; Play

      %a.teaser-animation-control-replay{href: 'javascript:void(0)', onclick: 'teaser_animation.replay();', title: 'wanna replay our awesome animation?'} &middot; Replay
      
      %a.teaser-animation-control-skip{href: 'javascript:void(0)', onclick: 'teaser_animation.skip();', title: 'you must be crazy to skip this awesome animation'} &middot; Skip